# Generated by Django 4.1.4 on 2022-12-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('pic', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
            ],
        ),
    ]
